#!/usr/bin/env bash

# gcc
sudo apt install gcc libc6-dev -y

# x11
sudo apt install libx11-dev xorg-dev libxtst-dev -y

# Clipboard
sudo apt install xsel xclip -y

#
# Bitmap
sudo apt install libpng++-dev -y

# GoHook
sudo apt install xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev -y
