#!/usr/bin/env bash
curl https://helldivers.wiki.gg/images/thumb/e/e0/Machine_Gun_Stratagem_Icon.png/50px-Machine_Gun_Stratagem_Icon.png?3dfe18 -o 0.png
curl https://helldivers.wiki.gg/images/thumb/3/3c/Anti-Materiel_Rifle_Stratagem_Icon.png/50px-Anti-Materiel_Rifle_Stratagem_Icon.png?fcf5b1 -o 1.png
curl https://helldivers.wiki.gg/images/thumb/4/46/Stalwart_Stratagem_Icon.png/50px-Stalwart_Stratagem_Icon.png?b35d66 -o 2.png
curl https://helldivers.wiki.gg/images/thumb/1/1c/Expendable_Anti-Tank_Stratagem_Icon.png/50px-Expendable_Anti-Tank_Stratagem_Icon.png?2634c5 -o 3.png
curl https://helldivers.wiki.gg/images/thumb/7/70/Recoilless_Rifle_Stratagem_Icon.png/50px-Recoilless_Rifle_Stratagem_Icon.png?44fee2 -o 4.png
curl https://helldivers.wiki.gg/images/thumb/7/75/Flamethrower_Stratagem_Icon.png/50px-Flamethrower_Stratagem_Icon.png?f36171 -o 5.png
curl https://helldivers.wiki.gg/images/thumb/e/ef/Autocannon_Stratagem_Icon.png/50px-Autocannon_Stratagem_Icon.png?fcd624 -o 6.png
curl https://helldivers.wiki.gg/images/thumb/d/d9/Heavy_Machine_Gun_Stratagem_Icon.png/50px-Heavy_Machine_Gun_Stratagem_Icon.png?910281 -o 7.png
curl https://helldivers.wiki.gg/images/thumb/a/ad/RL-77_Airburst_Rocket_Launcher_Stratagem_Icon.png/50px-RL-77_Airburst_Rocket_Launcher_Stratagem_Icon.png?ccc753 -o 8.png
curl https://helldivers.wiki.gg/images/thumb/7/78/Commando_Stratagem_Icon.png/50px-Commando_Stratagem_Icon.png?30c1d0 -o 9.png
curl https://helldivers.wiki.gg/images/thumb/3/35/Railgun_Stratagem_Icon.png/50px-Railgun_Stratagem_Icon.png?91c54b -o 10.png
curl https://helldivers.wiki.gg/images/thumb/5/54/Spear_Stratagem_Icon.png/50px-Spear_Stratagem_Icon.png?a47c14 -o 11.png
curl https://helldivers.wiki.gg/images/thumb/a/af/StA-X3_W.A.S.P._Launcher_Stratagem_Icon.png/50px-StA-X3_W.A.S.P._Launcher_Stratagem_Icon.png?c5c842 -o 12.png
curl https://helldivers.wiki.gg/images/thumb/f/f6/Orbital_Gatling_Barrage_Stratagem_Icon.png/50px-Orbital_Gatling_Barrage_Stratagem_Icon.png?17a44b -o 13.png
curl https://helldivers.wiki.gg/images/thumb/2/28/Orbital_Airburst_Strike_Stratagem_Icon.png/50px-Orbital_Airburst_Strike_Stratagem_Icon.png?d48d6a -o 14.png
curl https://helldivers.wiki.gg/images/thumb/4/40/Orbital_120mm_HE_Barrage_Stratagem_Icon.png/50px-Orbital_120mm_HE_Barrage_Stratagem_Icon.png?e120a8 -o 15.png
curl https://helldivers.wiki.gg/images/thumb/1/12/Orbital_380mm_HE_Barrage_Stratagem_Icon.png/50px-Orbital_380mm_HE_Barrage_Stratagem_Icon.png?7ed57e -o 16.png
curl https://helldivers.wiki.gg/images/thumb/5/53/Orbital_Walking_Barrage_Stratagem_Icon.png/50px-Orbital_Walking_Barrage_Stratagem_Icon.png?c596dd -o 17.png
curl https://helldivers.wiki.gg/images/thumb/d/d8/Orbital_Laser_Stratagem_Icon.png/50px-Orbital_Laser_Stratagem_Icon.png?4dbbd2 -o 18.png
curl https://helldivers.wiki.gg/images/thumb/9/97/Orbital_Napalm_Barrage_Stratagem_Icon.png/50px-Orbital_Napalm_Barrage_Stratagem_Icon.png?e6fc05 -o 19.png
curl https://helldivers.wiki.gg/images/thumb/6/6f/Orbital_Railcannon_Strike_Stratagem_Icon.png/50px-Orbital_Railcannon_Strike_Stratagem_Icon.png?e99667 -o 20.png
curl https://helldivers.wiki.gg/images/thumb/f/f3/Eagle_Strafing_Run_Stratagem_Icon.png/50px-Eagle_Strafing_Run_Stratagem_Icon.png?e6ad30 -o 21.png
curl https://helldivers.wiki.gg/images/thumb/7/72/Eagle_Airstrike_Stratagem_Icon.png/50px-Eagle_Airstrike_Stratagem_Icon.png?685944 -o 22.png
curl https://helldivers.wiki.gg/images/thumb/4/4f/Eagle_Cluster_Bomb_Stratagem_Icon.png/50px-Eagle_Cluster_Bomb_Stratagem_Icon.png?4c4860 -o 23.png
curl https://helldivers.wiki.gg/images/thumb/4/42/Eagle_Napalm_Airstrike_Stratagem_Icon.png/50px-Eagle_Napalm_Airstrike_Stratagem_Icon.png?ab5aa8 -o 24.png
curl https://helldivers.wiki.gg/images/thumb/f/f5/Jump_Pack_Stratagem_Icon.png/50px-Jump_Pack_Stratagem_Icon.png?b2b166 -o 25.png
curl https://helldivers.wiki.gg/images/thumb/0/05/Eagle_Smoke_Strike_Stratagem_Icon.png/50px-Eagle_Smoke_Strike_Stratagem_Icon.png?1cd323 -o 26.png
curl https://helldivers.wiki.gg/images/thumb/e/ef/Eagle_110mm_Rocket_Pods_Stratagem_Icon.png/50px-Eagle_110mm_Rocket_Pods_Stratagem_Icon.png?f9934d -o 27.png
curl https://helldivers.wiki.gg/images/thumb/e/e5/Eagle_500kg_Bomb_Stratagem_Icon.png/50px-Eagle_500kg_Bomb_Stratagem_Icon.png?ff6faf -o 28.png
curl https://helldivers.wiki.gg/images/thumb/0/00/M-102_Fast_Recon_Vehicle_Stratagem_Icon.png/50px-M-102_Fast_Recon_Vehicle_Stratagem_Icon.png?8cb2ad -o 29.png
curl https://helldivers.wiki.gg/images/thumb/2/2a/Orbital_Precision_Strike_Stratagem_Icon.png/50px-Orbital_Precision_Strike_Stratagem_Icon.png?561f51 -o 30.png
curl https://helldivers.wiki.gg/images/thumb/c/cd/Orbital_Gas_Strike_Stratagem_Icon.png/50px-Orbital_Gas_Strike_Stratagem_Icon.png?5d9ba4 -o 31.png
curl https://helldivers.wiki.gg/images/thumb/1/16/Orbital_EMS_Strike_Stratagem_Icon.png/50px-Orbital_EMS_Strike_Stratagem_Icon.png?77534f -o 32.png
curl https://helldivers.wiki.gg/images/thumb/b/bc/Orbital_Smoke_Strike_Stratagem_Icon.png/50px-Orbital_Smoke_Strike_Stratagem_Icon.png?a063f8 -o 33.png
curl https://helldivers.wiki.gg/images/thumb/0/03/HMG_Emplacement_Stratagem_Icon.png/50px-HMG_Emplacement_Stratagem_Icon.png?5f9e66 -o 34.png
curl https://helldivers.wiki.gg/images/thumb/e/e4/Shield_Generator_Relay_Stratagem_Icon.png/50px-Shield_Generator_Relay_Stratagem_Icon.png?64b940 -o 35.png
curl https://helldivers.wiki.gg/images/thumb/8/8f/Tesla_Tower_Stratagem_Icon.png/50px-Tesla_Tower_Stratagem_Icon.png?81457b -o 36.png
curl https://helldivers.wiki.gg/images/thumb/3/3f/GL-21_Grenadier_Battlement_Stratagem_Icon.png/50px-GL-21_Grenadier_Battlement_Stratagem_Icon.png?747ef0 -o 37.png
curl https://helldivers.wiki.gg/images/thumb/b/bb/Anti-Personnel_Minefield_Stratagem_Icon.png/50px-Anti-Personnel_Minefield_Stratagem_Icon.png?6887f0 -o 38.png
curl https://helldivers.wiki.gg/images/thumb/6/61/Supply_Pack_Stratagem_Icon.png/50px-Supply_Pack_Stratagem_Icon.png?90980d -o 39.png
curl https://helldivers.wiki.gg/images/thumb/c/cf/Grenade_Launcher_Stratagem_Icon.png/50px-Grenade_Launcher_Stratagem_Icon.png?b2eee9 -o 40.png
curl https://helldivers.wiki.gg/images/thumb/c/c3/Laser_Cannon_Stratagem_Icon.png/50px-Laser_Cannon_Stratagem_Icon.png?95398f -o 41.png
curl https://helldivers.wiki.gg/images/thumb/4/40/Incendiary_Mines_Stratagem_Icon.png/50px-Incendiary_Mines_Stratagem_Icon.png?b0bff9 -o 42.png
curl https://helldivers.wiki.gg/images/thumb/6/6f/Guard_Dog_Rover_Stratagem_Icon.png/50px-Guard_Dog_Rover_Stratagem_Icon.png?7ad22e -o 43.png
curl https://helldivers.wiki.gg/images/thumb/3/37/Ballistic_Shield_Backpack_Stratagem_Icon.png/50px-Ballistic_Shield_Backpack_Stratagem_Icon.png?ace094 -o 44.png
curl https://helldivers.wiki.gg/images/thumb/1/10/Arc_Thrower_Stratagem_Icon.png/50px-Arc_Thrower_Stratagem_Icon.png?63ff8b -o 45.png
curl https://helldivers.wiki.gg/images/thumb/b/ba/MD-17_Anti-Tank_Mines_Stratagem_Icon.png/50px-MD-17_Anti-Tank_Mines_Stratagem_Icon.png?589106 -o 46.png
curl https://helldivers.wiki.gg/images/thumb/8/87/Quasar_Cannon_Stratagem_Icon.png/50px-Quasar_Cannon_Stratagem_Icon.png?3e527d -o 47.png
curl https://helldivers.wiki.gg/images/thumb/9/99/Shield_Generator_Pack_Stratagem_Icon.png/50px-Shield_Generator_Pack_Stratagem_Icon.png?d35b0f -o 48.png
curl https://helldivers.wiki.gg/images/thumb/1/13/Gas_Minefield_Stratagem_Icon.png/50px-Gas_Minefield_Stratagem_Icon.png?3b8000 -o 49.png
curl https://helldivers.wiki.gg/images/thumb/5/5a/Machine_Gun_Sentry_Stratagem_Icon.png/50px-Machine_Gun_Sentry_Stratagem_Icon.png?3998e1 -o 50.png
curl https://helldivers.wiki.gg/images/thumb/2/28/Gatling_Sentry_Stratagem_Icon.png/50px-Gatling_Sentry_Stratagem_Icon.png?b959a4 -o 51.png
curl https://helldivers.wiki.gg/images/thumb/a/ad/Mortar_Sentry_Stratagem_Icon.png/50px-Mortar_Sentry_Stratagem_Icon.png?1252af -o 52.png
curl https://helldivers.wiki.gg/images/thumb/7/73/Guard_Dog_Stratagem_Icon.png/50px-Guard_Dog_Stratagem_Icon.png?61d1b4 -o 53.png
curl https://helldivers.wiki.gg/images/thumb/a/a7/Autocannon_Sentry_Stratagem_Icon.png/50px-Autocannon_Sentry_Stratagem_Icon.png?bae013 -o 54.png
curl https://helldivers.wiki.gg/images/thumb/6/62/Rocket_Sentry_Stratagem_Icon.png/50px-Rocket_Sentry_Stratagem_Icon.png?f65e40 -o 55.png
curl https://helldivers.wiki.gg/images/thumb/a/a8/AM-23_EMS_Mortar_Sentry_Stratagem_Icon.png/50px-AM-23_EMS_Mortar_Sentry_Stratagem_Icon.png?f0de8a -o 56.png
curl https://helldivers.wiki.gg/images/thumb/3/30/EXO-45_Patriot_Exosuit_Stratagem_Icon.png/50px-EXO-45_Patriot_Exosuit_Stratagem_Icon.png?64a72f -o 57.png
curl https://helldivers.wiki.gg/images/thumb/8/82/EXO-49_Emancipator_Exosuit_Stratagem_Icon.png/50px-EXO-49_Emancipator_Exosuit_Stratagem_Icon.png?6f2e3c -o 58.png
curl https://helldivers.wiki.gg/images/thumb/2/29/Sterilizer_Stratagem_Icon.png/50px-Sterilizer_Stratagem_Icon.png?5f6a3c -o 59.png
curl https://helldivers.wiki.gg/images/thumb/2/20/Guard_Dog_Dog_Breath_Stratagem_Icon.png/50px-Guard_Dog_Dog_Breath_Stratagem_Icon.png?9e6385 -o 60.png
curl https://helldivers.wiki.gg/images/thumb/b/b7/SH-51_Directional_Shield_Stratagem_Icon.png/50px-SH-51_Directional_Shield_Stratagem_Icon.png?4e63ec -o 61.png
curl https://helldivers.wiki.gg/images/thumb/6/62/E_AT-12_Anti-Tank_Emplacement_Stratagem_Icon.png/50px-E_AT-12_Anti-Tank_Emplacement_Stratagem_Icon.png?3fbc70 -o 62.png
curl https://helldivers.wiki.gg/images/thumb/0/0e/A_FLAM-40_Flame_Sentry_Stratagem_Icon.png/50px-A_FLAM-40_Flame_Sentry_Stratagem_Icon.png?c4c859 -o 63.png
curl https://helldivers.wiki.gg/images/thumb/a/aa/Portable_Hellbomb_Stratagem_Icon.png/50px-Portable_Hellbomb_Stratagem_Icon.png?c9a263 -o 64.png
curl https://helldivers.wiki.gg/images/thumb/5/5d/Hover_Pack_Stratagem_Icon.png/50px-Hover_Pack_Stratagem_Icon.png?a00cb1 -o 65.png
curl https://helldivers.wiki.gg/images/thumb/5/5c/Reinforce_Stratagem_Icon.png/50px-Reinforce_Stratagem_Icon.png?653984 -o 66.png
curl https://helldivers.wiki.gg/images/thumb/3/3d/SOS_Beacon_Stratagem_Icon.png/50px-SOS_Beacon_Stratagem_Icon.png?21c230 -o 67.png
curl https://helldivers.wiki.gg/images/thumb/6/64/Resupply_Stratagem_Icon.png/50px-Resupply_Stratagem_Icon.png?874804 -o 68.png
curl https://helldivers.wiki.gg/images/thumb/0/08/Eagle_Rearm_Stratagem_Icon.png/50px-Eagle_Rearm_Stratagem_Icon.png?1d2fc1 -o 69.png
curl https://helldivers.wiki.gg/images/5/53/Start_Upload_Stratagem_Icon.svg?4c4715 -o 70.png
curl https://helldivers.wiki.gg/images/thumb/0/02/Prospecting_Drill_Stratagem_Icon.png/50px-Prospecting_Drill_Stratagem_Icon.png?1ab95c -o 71.png
curl https://helldivers.wiki.gg/images/thumb/3/3c/Super_Earth_Flag_Stratagem_Icon.png/50px-Super_Earth_Flag_Stratagem_Icon.png?4c5f80 -o 72.png
curl https://helldivers.wiki.gg/images/thumb/a/a0/Hellbomb_Stratagem_Icon.png/50px-Hellbomb_Stratagem_Icon.png?6c240b -o 73.png
curl https://helldivers.wiki.gg/images/5/53/Start_Upload_Stratagem_Icon.svg?4c4715 -o 74.png
curl https://helldivers.wiki.gg/images/thumb/7/74/Seismic_Probe_Stratagem_Icon.png/50px-Seismic_Probe_Stratagem_Icon.png?e1a0e3 -o 75.png
curl https://helldivers.wiki.gg/images/thumb/f/f9/Orbital_Illumination_Flare_Stratagem_Icon.png/50px-Orbital_Illumination_Flare_Stratagem_Icon.png?9a63e8 -o 76.png
curl https://helldivers.wiki.gg/images/thumb/f/f7/SEAF_Artillery_Stratagem_Icon.png/50px-SEAF_Artillery_Stratagem_Icon.png?19a114 -o 77.png
curl https://helldivers.wiki.gg/images/thumb/7/7b/Dark_Fluid_Vessel_Stratagem_Icon.png/50px-Dark_Fluid_Vessel_Stratagem_Icon.png?ddd0df -o 78.png
curl https://helldivers.wiki.gg/images/thumb/0/02/Prospecting_Drill_Stratagem_Icon.png/50px-Prospecting_Drill_Stratagem_Icon.png?1ab95c -o 79.png
curl https://helldivers.wiki.gg/images/thumb/0/02/Prospecting_Drill_Stratagem_Icon.png/50px-Prospecting_Drill_Stratagem_Icon.png?1ab95c -o 80.png
